export default {
  user: "user",
  drawerOpen: false,
  allStrains: {},
  searchParams: "",
  userSearchInput: "",
  userSearchResults: [],
  effects: {
    positive: [],
    negative: [],
    medical: [],
  },
  flavors: [],
  strainDescription: "",
  speciesPrefs: [],
  posPrefs: [],
  avoidPrefs: [],
  medPrefs: [],
  flavPrefs: [],
};
